[package]
name = "mesh_tool"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2021"

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
grim = { path = "../grim", features = [ "model" ] }
thiserror = "1.0.30"
