[package]
name = "milo_export"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
grim = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
