[package]
name = "mesh_tool"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
grim = { workspace = true, features = [ "model" ] }
thiserror = { workspace = true }

[features]
experimental = []